[workspace]
resolver = "2"

members = [
    "types",
    "bytecode",
    "vm",
    "assembler",
    "ast",
    "parser",
    "lexer",
    "environment",
    "builder",
    "compiler",
    "import_test",
    "abi",
]
