[package]
name = "xelis-types"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.7.0", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.1"

[features]
value_pointer_drop = []
